//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeItKnowIt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeeItKnowIt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already running.
        /// </summary>
        internal static string Application_AlreadyRunningMessage {
            get {
                return ResourceManager.GetString("Application_AlreadyRunningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0}.
        /// </summary>
        internal static string Application_WelcomeMessage {
            get {
                return ResourceManager.GetString("Application_WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap both_left {
            get {
                object obj = ResourceManager.GetObject("both_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap both_left_disabled {
            get {
                object obj = ResourceManager.GetObject("both_left_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap both_right {
            get {
                object obj = ResourceManager.GetObject("both_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap both_right_disabled {
            get {
                object obj = ResourceManager.GetObject("both_right_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ButtonCloseToolTip {
            get {
                return ResourceManager.GetString("ButtonCloseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string ButtonPastWordsToolTip {
            get {
                return ResourceManager.GetString("ButtonPastWordsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        internal static string ButtonPinToolTip {
            get {
                return ResourceManager.GetString("ButtonPinToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the translation language.
        /// </summary>
        internal static string ComboBoxLanguageToolTip {
            get {
                return ResourceManager.GetString("ComboBoxLanguageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap config {
            get {
                object obj = ResourceManager.GetObject("config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap config_taskbar {
            get {
                object obj = ResourceManager.GetObject("config_taskbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter language here....
        /// </summary>
        internal static string Configuration_AddLanguage_EditWatermark {
            get {
                return ResourceManager.GetString("Configuration_AddLanguage_EditWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language name cannot contain &apos;{0}&apos;.
        /// </summary>
        internal static string Configuration_AddLanguage_InvalidLanguage {
            get {
                return ResourceManager.GetString("Configuration_AddLanguage_InvalidLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added language: {0}, remember to add a lookup site before using it..
        /// </summary>
        internal static string Configuration_AddLanguage_Success {
            get {
                return ResourceManager.GetString("Configuration_AddLanguage_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new language below:.
        /// </summary>
        internal static string Configuration_AddLanguage_Title {
            get {
                return ResourceManager.GetString("Configuration_AddLanguage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter URL here....
        /// </summary>
        internal static string Configuration_AddSite_EditWatermark {
            get {
                return ResourceManager.GetString("Configuration_AddSite_EditWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL must contain {{0}}.
        /// </summary>
        internal static string Configuration_AddSite_LabelError_IncompatibleURL {
            get {
                return ResourceManager.GetString("Configuration_AddSite_LabelError_IncompatibleURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL format, please check again.
        /// </summary>
        internal static string Configuration_AddSite_LabelError_InvalidURL {
            get {
                return ResourceManager.GetString("Configuration_AddSite_LabelError_InvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter chosen word above.
        /// </summary>
        internal static string Configuration_AddSite_LabelError_MissingWord {
            get {
                return ResourceManager.GetString("Configuration_AddSite_LabelError_MissingWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter chosen word here....
        /// </summary>
        internal static string Configuration_AddSite_LookupWordWatermark {
            get {
                return ResourceManager.GetString("Configuration_AddSite_LookupWordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new lookup site below: (help?       ).
        /// </summary>
        internal static string Configuration_AddSite_Title {
            get {
                return ResourceManager.GetString("Configuration_AddSite_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add a lookup site from {0} to {1}:\n- Open your site in a web browser and look up any {0} word\n- Copy the final URL, replace ALL occurences of the lookup word by {{0}}\n- Example: http://mysite.com/word becomes http://mysite.com/{{0}}.
        /// </summary>
        internal static string Configuration_AddSite_Tutorial {
            get {
                return ResourceManager.GetString("Configuration_AddSite_Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this language? This will also delete all associated lookup sites and close any opened lookup window..
        /// </summary>
        internal static string Configuration_DeleteLanguage_Confirmation {
            get {
                return ResourceManager.GetString("Configuration_DeleteLanguage_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete language: {0}, please try again..
        /// </summary>
        internal static string Configuration_DeleteLanguage_Failure {
            get {
                return ResourceManager.GetString("Configuration_DeleteLanguage_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete a default language.
        /// </summary>
        internal static string Configuration_DeleteLanguage_LabelError_DefaultLanguage {
            get {
                return ResourceManager.GetString("Configuration_DeleteLanguage_LabelError_DefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted language: {0}..
        /// </summary>
        internal static string Configuration_DeleteLanguage_Success {
            get {
                return ResourceManager.GetString("Configuration_DeleteLanguage_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this site?.
        /// </summary>
        internal static string Configuration_DeleteSite_Confirmation {
            get {
                return ResourceManager.GetString("Configuration_DeleteSite_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey:.
        /// </summary>
        internal static string Configuration_HotkeyCombinationLabel {
            get {
                return ResourceManager.GetString("Configuration_HotkeyCombinationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default lookup mode:.
        /// </summary>
        internal static string Configuration_Label_Languages {
            get {
                return ResourceManager.GetString("Configuration_Label_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore all default settings:.
        /// </summary>
        internal static string Configuration_Label_RestoreSettings {
            get {
                return ResourceManager.GetString("Configuration_Label_RestoreSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string Configuration_Label_To {
            get {
                return ResourceManager.GetString("Configuration_Label_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current lookup sites: (Add new?       ).
        /// </summary>
        internal static string Configuration_Label_TranslateSites {
            get {
                return ResourceManager.GetString("Configuration_Label_TranslateSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new language....
        /// </summary>
        internal static string Configuration_Language_AddNew {
            get {
                return ResourceManager.GetString("Configuration_Language_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or select a language to delete:.
        /// </summary>
        internal static string Configuration_Language_Delete {
            get {
                return ResourceManager.GetString("Configuration_Language_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t assign the selected hotkey combination, please choose a different value..
        /// </summary>
        internal static string Configuration_RegisterHotKey_Failure {
            get {
                return ResourceManager.GetString("Configuration_RegisterHotKey_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t assign default hotkey to activate the application, please update manually from Configuration settings. .
        /// </summary>
        internal static string Configuration_RegisterHotKey_FirstUse_Failure {
            get {
                return ResourceManager.GetString("Configuration_RegisterHotKey_FirstUse_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey was successfully registered..
        /// </summary>
        internal static string Configuration_RegisterHotKey_Success {
            get {
                return ResourceManager.GetString("Configuration_RegisterHotKey_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restore all settings to default?.
        /// </summary>
        internal static string Configuration_RestoreSettings_Confirmation {
            get {
                return ResourceManager.GetString("Configuration_RestoreSettings_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string Configuration_RestoreText {
            get {
                return ResourceManager.GetString("Configuration_RestoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully restored all settings..
        /// </summary>
        internal static string Configuration_SuccessfulRestore {
            get {
                return ResourceManager.GetString("Configuration_SuccessfulRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new site.
        /// </summary>
        internal static string Configuration_TranslateSite_AddNew {
            get {
                return ResourceManager.GetString("Configuration_TranslateSite_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete a default site.
        /// </summary>
        internal static string Configuration_TranslateSite_DeleteButton_DisabledToolTip {
            get {
                return ResourceManager.GetString("Configuration_TranslateSite_DeleteButton_DisabledToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this site.
        /// </summary>
        internal static string Configuration_TranslateSite_DeleteButton_EnabledToolTip {
            get {
                return ResourceManager.GetString("Configuration_TranslateSite_DeleteButton_EnabledToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this site.
        /// </summary>
        internal static string Configuration_TranslateSite_MakeActive {
            get {
                return ResourceManager.GetString("Configuration_TranslateSite_MakeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Version {1}.
        /// </summary>
        internal static string Configuration_VersionInfo {
            get {
                return ResourceManager.GetString("Configuration_VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_disabled {
            get {
                object obj = ResourceManager.GetObject("delete_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Dialog_Confirmation {
            get {
                return ResourceManager.GetString("Dialog_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Dialog_Error {
            get {
                return ResourceManager.GetString("Dialog_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Dialog_Information {
            get {
                return ResourceManager.GetString("Dialog_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Dialog_Success {
            get {
                return ResourceManager.GetString("Dialog_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Dialog_Warning {
            get {
                return ResourceManager.GetString("Dialog_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided URL has an invalid format, please update from configuration settings..
        /// </summary>
        internal static string Error_InvalidUriFormat {
            get {
                return ResourceManager.GetString("Error_InvalidUriFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Delete....
        /// </summary>
        internal static string General_Add_Delete {
            get {
                return ResourceManager.GetString("General_Add_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight any text then press {0} to look up its meaning.
        /// </summary>
        internal static string Information_Tutorial {
            get {
                return ResourceManager.GetString("Information_Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap left {
            get {
                object obj = ResourceManager.GetObject("left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pastwords {
            get {
                object obj = ResourceManager.GetObject("pastwords", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pin {
            get {
                object obj = ResourceManager.GetObject("pin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plus_disabled {
            get {
                object obj = ResourceManager.GetObject("plus_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap right {
            get {
                object obj = ResourceManager.GetObject("right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tip {
            get {
                object obj = ResourceManager.GetObject("tip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tip_disabled {
            get {
                object obj = ResourceManager.GetObject("tip_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is running.
        /// </summary>
        internal static string TrayIcon_BalloonTipText {
            get {
                return ResourceManager.GetString("TrayIcon_BalloonTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        internal static string TrayIcon_MenuItem_Configuration {
            get {
                return ResourceManager.GetString("TrayIcon_MenuItem_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string TrayIcon_MenuItem_Exit {
            get {
                return ResourceManager.GetString("TrayIcon_MenuItem_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        internal static string TrayIcon_Text {
            get {
                return ResourceManager.GetString("TrayIcon_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;font size=4&gt;Loading... Taking too long? &lt;a href=&quot;{0}&quot;&gt;Reload&lt;/a&gt;&lt;/font&gt;.
        /// </summary>
        internal static string WebBrowser_LoadingHTMLText {
            get {
                return ResourceManager.GetString("WebBrowser_LoadingHTMLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;font size=4&gt;There&apos;s no corresponding sites for lookup from {0} to {1}. Please visit Configuration and add a site.&lt;/font&gt;.
        /// </summary>
        internal static string WebBrowser_SiteURLMissingText {
            get {
                return ResourceManager.GetString("WebBrowser_SiteURLMissingText", resourceCulture);
            }
        }
    }
}
